const RCC_ADDR = 0x4002_1000;

const RccRegister = packed struct {
    CR: packed struct(u32) {
        HSION: u1,
        HSIRDY: u1,
        _rsvd1: u1,
        HSITRIM: u5,
        HSICAL: u8,
        HSEON: u1,
        HSERDY: u1,
        HSEBYP: u1,
        CSSON: u1,
        _rsvd2: u4,
        PLLON: u1,
        PLLRDY: u1,
        _rsvd3: u6,
    },
    CFGR: packed struct(u32) {
        SW: u2,
        SWS: u2,
        HPRE: u4,
        PPRE1: u3,
        PPRE2: u3,
        ADCPRE: u2,
        PLLSRC: u1,
        PLLXTPRE: u1,
        PLLMUL: u4,
        USBPRE: u1,
        _rsvd1: u1,
        MCO: u3,
        _rsvd2: u5,
    },
    CIR: u32, // TODO
    APB2RSTR: u32, // TODO
    APB1RSTR: u32, // TODO
    ENR: packed struct {
        // AHBENR
        DMA1EN: u1,
        DMA2EN: u1,
        SRAMEN: u1,
        _rsvd1: u1,
        FLITFEN: u1,
        _rsvd2: u1,
        CRCEN: u1,
        _rsvd3: u1,
        FSMCEN: u1,
        _rsvd4: u1,
        SDIOEN: u1,
        _rsvd5: u21,

        // APB2ENR
        AFIOEN: u1,
        _rsvd6: u1,
        IOPAEN: u1,
        IOPBEN: u1,
        IOPCEN: u1,
        IOPDEN: u1,
        IOPEEN: u1,
        IOPFEN: u1,
        IOPGEN: u1,
        ADC1EN: u1,
        ADC2EN: u1,
        TIM1EN: u1,
        SPI1EN: u1,
        TIM8EN: u1,
        USART1EN: u1,
        ADC3EN: u1,
        _rsvd7: u3,
        TIM9EN: u1,
        TIM10EN: u1,
        TIM11EN: u1,
        _rsvd8: u10,

        // APB1ENR
        TIM2EN: u1,
        TIM3EN: u1,
        TIM4EN: u1,
        TIM5EN: u1,
        TIM6EN: u1,
        TIM7EN: u1,
        TIM12EN: u1,
        TIM13EN: u1,
        TIM14EN: u1,
        _rsvd9: u2,
        WWDGEN: u1,
        _rsvd10: u2,
        SPI2EN: u1,
        SPI3EN: u1,
        _rsvd11: u1,
        USART2EN: u1,
        USART3EN: u1,
        UART4EN: u1,
        UART5EN: u1,
        I2C1EN: u1,
        I2C2EN: u1,
        USBEN: u1,
        _rsvd12: u1,
        CANEN: u1,
        _rsvd13: u1,
        BKPEN: u1,
        PWREN: u1,
        DACEN: u1,
        _rsvd14: u2,
    },
    BDCR: u32, // TODO
    CSR: u32, // TODO
};

pub const RCC: *volatile RccRegister = @ptrFromInt(RCC_ADDR);
